fix(Loader): restored compatibility with older versions of Unity
Changed `is null` with `== null` to solve in older versions of Unity the
`error CS1644: Feature 'pattern matching' cannot be used because it is
not part of the C# 4.0 language specification.`